Repository cloud-native-toolkit/terraform-gitops-cp-mq, pull requests merged in 2021-12, with the labels that each got.

#1 Remove API Keys
  .github/scripts/validate-deploy.sh
  .github/workflows/verify.yaml
  test/stages/stage1-resource-group.tf
  test/stages/stage2-mymodule.tf
  version.tf
Labels: enhancement, major

#2 Update README
  README.md
Labels: enhancement, minor

#3 Updates verify workflow logic for getting the gitops repo org and name
  .github/workflows/verify.yaml
  test/stages/stage1-gitops.tf
Labels: patch, chore
